create table if not exists roles (
    id bigint generated by default as identity primary key,
    name varchar(100) not null unique,
    description varchar(500)
);

create table if not exists permissions (
    id bigint generated by default as identity primary key,
    name varchar(150) not null unique,
    description varchar(500)
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    enabled boolean not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table if not exists user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_roles_role foreign key (role_id) references roles (id) on delete cascade
);

create table if not exists role_permissions (
    role_id bigint not null,
    permission_id bigint not null,
    primary key (role_id, permission_id),
    constraint fk_role_permissions_role foreign key (role_id) references roles (id) on delete cascade,
    constraint fk_role_permissions_permission foreign key (permission_id) references permissions (id) on delete cascade
);
