create table if not exists admin_content (
    id bigint generated by default as identity primary key,
    type varchar(50) not null,
    title varchar(255) not null,
    status varchar(50) not null,
    author varchar(120) not null,
    category varchar(120) not null,
    updated_at date not null
);

insert into admin_content (type, title, status, author, category, updated_at)
values
    ('news', 'اجتماع لمناقشة أولويات الخدمات الحكومية الرقمية', 'منشور', 'أحمد علي', 'الأخبار', '2026-08-16'),
    ('announcement', 'إعلان رسمي عن إطلاق المرحلة الأولى من البوابة الحكومية', 'مسودة', 'سارة محمد', 'الإعلانات', '2026-08-15'),
    ('decision', 'قرار اعتماد الهوية البصرية الرسمية', 'منشور', 'خالد اليماني', 'القرارات', '2026-08-12'),
    ('document', 'خطة النشر لمرحلة MVP', 'مؤرشف', 'منى المعلمي', 'الوثائق', '2026-08-10'),
    ('news', 'تحديثات تنظيمية على مسار النشر', 'قيد المراجعة', 'علي السامعي', 'الأخبار', '2026-08-09');
