create table if not exists support_requests (
    id bigint generated by default as identity primary key,
    full_name varchar(120) not null,
    email varchar(120) not null,
    phone varchar(30),
    category varchar(60) not null,
    subject varchar(180) not null,
    message text not null,
    created_at timestamp not null
);
